name: Bash GitHub Actions

on: [push, pull_request]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Package Helm Chart
       shell: bash
       run: |
          set -xeE -o pipefail
          sed -i 's/name: "hyper-project"/name: "hyper-acheem"/g' hello.txt
          ls -lrt
          
     - run: echo "One last message"