name: Bash GitHub Actions

on: [push, pull_request]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo "A initial message"
        echo "Another message or command"
     - run: echo "One last message"