on:
  push:
    branches: [ master ]
  pull_request:
  
name: Node Project `node-js-app` CI on ECR
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      run: |
        # Build a docker container and push it to ECR 
        IMAGE_TAG=${GITHUB_REF##*/}-${GITHUB_SHA}-$(date +%s)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
  build:
    env:
      HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
      HELM_VERSION_TO_INSTALL: 3.5.0 # version of HEL to install
    name: publish ecr
    runs-on: ubuntu-latest
    needs: [deploy]
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Helm Repo Add
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
         pwd
         ls -lrt
         IMAGE_TAG="heml-chart-${GITHUB_SHA}"
         helm chart save chart ${{ env.ECR_REGISTRY }}/${{ secrets.REPO_NAME }}:$IMAGE_TAG
         helm chart list
         aws ecr get-login-password --region ap-south-1 | helm registry login  --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
         helm chart push  ${{ env.ECR_REGISTRY }}/${{ secrets.REPO_NAME }}:$IMAGE_TAG
